management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
#      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
      defaultZone: ${DISCOVERY_SERVICE_URL:http://discovery-service:8761/eureka}
spring:
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8070